// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk7x3GtwSp5fCfFYSBRshMPKQz8UOa1Cs',
    appId: '1:387047781761:web:24f2c61a2e02adc1fae480',
    messagingSenderId: '387047781761',
    projectId: 'sotre-770a9',
    authDomain: 'sotre-770a9.firebaseapp.com',
    storageBucket: 'sotre-770a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA043bw1-vvuPpG_8QyOJqmKCrfWisoURQ',
    appId: '1:387047781761:android:a2bc9db9ca9c3561fae480',
    messagingSenderId: '387047781761',
    projectId: 'sotre-770a9',
    storageBucket: 'sotre-770a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq1uTogASMOfGV94BrO4r0InXTMMaP3LI',
    appId: '1:387047781761:ios:751c2ff17582fa96fae480',
    messagingSenderId: '387047781761',
    projectId: 'sotre-770a9',
    storageBucket: 'sotre-770a9.appspot.com',
    iosBundleId: 'com.example.sotreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq1uTogASMOfGV94BrO4r0InXTMMaP3LI',
    appId: '1:387047781761:ios:751c2ff17582fa96fae480',
    messagingSenderId: '387047781761',
    projectId: 'sotre-770a9',
    storageBucket: 'sotre-770a9.appspot.com',
    iosBundleId: 'com.example.sotreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk7x3GtwSp5fCfFYSBRshMPKQz8UOa1Cs',
    appId: '1:387047781761:web:d70098fd682c1257fae480',
    messagingSenderId: '387047781761',
    projectId: 'sotre-770a9',
    authDomain: 'sotre-770a9.firebaseapp.com',
    storageBucket: 'sotre-770a9.appspot.com',
  );
}
